---

- name: Node.js | Download Nodesource Install Script
  get_url:
    url: http://deb.nodesource.com/setup_{{ node_version }}
    dest: /tmp/setup_{{ node_version }}
    mode: 0777

- name: Node.js | Install Nodesource
  shell: bash /tmp/setup_{{ node_version }}

- name: Node.js | Install Node.js and npm
  apt: pkg=nodejs
  sudo: yes
  tags: nodejs

- name: Node.js | Update npm
  command: npm install -g npm@3.7.3
  sudo: yes
  tags: nodejs